- hosts: sata,nvme
  become: yes
  tasks:
   - name: setup sftp dir
     file:
       path: '/etc/systemd/system/sshd@.service.d'
       state: directory
       mode: '0755'

   - name: setup sftp config
     copy:
       src: sftp.conf
       dest: '/etc/systemd/system/sshd@.service.d/sftp.confg'
       owner: root
       mode: '0644'

   - name: reload systemd
     shell: systemctl daemon-reload

   - name: Install kvm-host and lvm
     shell: swupd bundle-add kvm-host storage-utils virt-manager >> swupd_kvm.txt
     args:
       chdir: $HOME
       creates: /usr/bin/virt-install

   - name: Create lvm drive
     shell: lvcreate -L 20G -n k8s --yes vms
     args:
       chdir: $HOME
       creates: /dev/vms/k8s

   - name: get coreos image
     shell: curl https://stable.release.core-os.net/amd64-usr/current/coreos_production_qemu_image.img.bz2 | bunzip2 -d - > coreos_production_qemu_image.img.qcow2 && qemu-img convert coreos_production_qemu_image.img.qcow2 coreos_production_qemu_image.img && rm coreos_production_qemu_image.img.qcow2
     args:
       chdir: $HOME
       creates: coreos_production_qemu_image.img

   - name: write image
     shell: dd if=coreos_production_qemu_image.img of=/dev/vms/k8s bs=1M status=progress >> dd_core.txt
     args:
       chdir: $HOME
       creates: dd_core.txt

   - name: Make sure libvirtd is enabled
     systemd:
       name: libvirtd
       state: started
       enabled: yes

   - name: Make sure libvirt-guests is enabled
     systemd:
       name: libvirt-guests
       state: started
       enabled: yes

   - name: copy ignition config
     copy:
       src: ssh.ign
       dest: /var/lib/libvirt/qemu/k8s-ssh.ign
       owner: root
       group: root
       mode: '0644'

   - name: setup domain.xml
     shell: virt-install --connect qemu:///system --import --name k8s --ram 3840 --network network=k8s,model=virtio --vcpus 4 --os-type=linux  --os-variant=virtio26 --disk path=/dev/vms/k8s,bus=virtio --vnc --noautoconsole --print-xml > /root/k8s.xml && sed -i 's|type="kvm"|type="kvm" xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0"|' /root/k8s.xml && sed -i "/<\/devices>/a <qemu:commandline>\n  <qemu:arg value='-fw_cfg'/>\n  <qemu:arg value='name=opt/com.coreos/config,file=/var/lib/libvirt/qemu/k8s-ssh.ign'/>\n</qemu:commandline>" /root/k8s.xml
     args:
       creates: /root/k8s.xml

   - name: copy bridge network
     copy:
       src: bridge.xml
       dest: /root/bridge.xml
       owner: root
       group: root
       mode: '0644'

   - name: define bridge network
     shell: virsh net-define /root/bridge.xml && virsh net-start k8s && virsh net-autostart k8s
     args:
       chdir: $HOME
       creates: /etc/libvirt/qemu/networks/k8s.xml

   - name: define and start domain
     shell: virsh define /root/k8s.xml && virsh autostart k8s && virsh start k8s
     args:
       creates: /etc/libvirt/qemu/k8s.xml
